import { useEffect, useMemo, useState } from 'react';
import Header from '../../components/layout/Header';
import Card from '../../components/ui/Card';
import TaskRow from '../../components/ui/TaskRow';
import EmptyState from '../../components/ui/EmptyState';
import IconButton from '../../components/ui/IconButton';
import { useLocale, formatString } from '../../i18n/LocaleContext';
import { useAppState } from '../../state/AppStateContext';
import { expandTaskOccurrences, resolveCompletedTaskOccurrences } from '../../lib/occurrences';
import { describeRecurrence } from '../../lib/recurrence';
import { toISODate, addDays, formatTaskRowDateLabel } from '../../lib/utils';
import type { Task } from '../../types/task';
import AddTaskSheet from './AddTaskSheet';
import TaskDetailsSheet from './TaskDetailsSheet';
import './TasksPage.css';

type Filter = 'all' | 'today' | 'overdue' | 'upcoming' | 'completed';

// A reasonable planning horizon for expanding recurring series into the
// "Upcoming" list — showing every future occurrence forever would be
// both unbounded and overwhelming for a flat backlog-style view.
const UPCOMING_HORIZON_DAYS = 60;

// How far back "Overdue" searches for a missed recurring occurrence.
//
// PRODUCT RULE (explicit, not silently arbitrary): search each
// recurring series from its OWN start date forward — i.e., include
// every occurrence the series has ever had, with no artificial cutoff —
// bounded only by a ~10-year defensive ceiling that exists purely as a
// backstop against pathological data (e.g. a manually mis-entered due
// date decades in the past), never as a realistic day-to-day limit.
//
// This is safe and cheap because of how getOccurrencesInRange (see
// src/lib/recurrence.ts) already works: it clamps its actual search
// start to whichever is LATER — the range passed in, or the series' own
// due date — so passing a very early PAST_HORIZON_DAYS here never makes
// a young series scan further back than the day it actually started.
// The function also has its own internal 3660-iteration (~10 year) cap
// regardless of what range is requested, so this can never become an
// unbounded or performance-dangerous loop even for pathological input.
// No database rows are generated by any of this — it's purely an
// in-memory date-range walk repeated on every recompute.
const PAST_HORIZON_DAYS = 3650;

/**
 * Whether a specific occurrence date (with its own effective due time,
 * which for an override is the OVERRIDE's own time, and for a plain
 * recurring occurrence is the series' consistent time-of-day) is overdue
 * as of right now.
 *   - any date before today -> overdue
 *   - today, with a due time that has already passed -> overdue
 *   - today, with no due time, or a due time still ahead -> NOT overdue
 *     (a task due today with no time is only overdue starting tomorrow)
 */
function isOccurrenceOverdue(
  occurrenceDate: string,
  dueTime: string | undefined,
  todayISO: string,
  nowTimeHHMM: string,
): boolean {
  if (occurrenceDate < todayISO) return true;
  if (occurrenceDate === todayISO && dueTime && dueTime < nowTimeHHMM) return true;
  return false;
}

export default function TasksPage() {
  const { t, locale } = useLocale();
  const {
    tasks,
    tasksLoading,
    tasksError,
    toggleTask,
    addTask,
    updateTask,
    deleteTask,
    deleteTaskOccurrence,
    saveTaskOccurrenceOverride,
    reminders,
    taskOccurrenceCompletions,
    taskOccurrenceSkips,
    taskOccurrenceCompletionRecords,
    setTaskOccurrenceCompletion,
  } = useAppState();
  const [filter, setFilter] = useState<Filter>('all');
  const [sheetOpen, setSheetOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [sheetHidesRecurrence, setSheetHidesRecurrence] = useState(false);
  const [overrideContext, setOverrideContext] = useState<{ seriesId: string; date: string } | null>(null);
  type FilteredRow = { row: Task; editTask: Task; occurrenceDate?: string; seriesId?: string };
  // Tapping a row now opens read-only details — editing only happens
  // after an explicit Edit action (the sheet's own Edit button, or a
  // swipe-left Edit). detailsInitialAction lets a swipe jump straight to
  // the sheet's existing Edit/Delete flow without a second tap, while
  // still going through that exact same logic (see TaskDetailsSheet's
  // initialAction prop).
  const [detailsRow, setDetailsRow] = useState<FilteredRow | null>(null);
  const [detailsInitialAction, setDetailsInitialAction] = useState<'edit' | 'delete' | null>(null);

  // "All" shows one row per recurring series (its current/next pending
  // occurrence) rather than every future date. Without this, completing
  // that occurrence's checkbox would immediately recompute to the NEXT
  // pending occurrence — making the checkbox look like it did nothing,
  // and letting repeated taps silently complete several future
  // occurrences in a row. Once a specific occurrence has been toggled
  // from All, this pins that exact date so All keeps showing it (now
  // reflecting its real, current completion state) instead of jumping
  // ahead — purely a display choice, not a change to how completion
  // itself is stored. Cleared whenever the filter changes (including
  // switching away and back to "all"), and naturally reset entirely on
  // leaving/re-entering the Tasks page, since this is local component
  // state.
  const [pinnedAllOccurrence, setPinnedAllOccurrence] = useState<Record<string, string>>({});
  useEffect(() => {
    setPinnedAllOccurrence({});
  }, [filter]);

  // How many of the newest completed items to show at once — an ITEM
  // count, not a date window, so it stays bounded regardless of how many
  // tasks a user completes in a short period. Resets back to the initial
  // batch whenever the filter changes (including leaving and returning
  // to "completed"), matching the same reset pattern already used for
  // pinnedAllOccurrence above.
  const COMPLETED_BATCH_SIZE = 30;
  const [completedVisibleCount, setCompletedVisibleCount] = useState(COMPLETED_BATCH_SIZE);
  useEffect(() => {
    setCompletedVisibleCount(COMPLETED_BATCH_SIZE);
  }, [filter]);

  // Drives "now" for overdue/date calculations below. Ticks once a
  // minute — never higher-frequency — which is exactly enough
  // resolution for a due TIME (HH:MM) to be detected as passed, and for
  // the date itself to correctly roll over at midnight, without a page
  // reload. A plain setInterval is used rather than requestAnimationFrame
  // or any per-second timer, since nothing here needs sub-minute
  // precision.
  const [now, setNow] = useState(() => new Date());
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 60000);
    return () => clearInterval(id);
  }, []);

  const todayISO = toISODate(now);
  const nowTimeHHMM = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

  const filters: { key: Filter; label: string }[] = [
    { key: 'all', label: t.tasks.filterAll },
    { key: 'today', label: t.tasks.filterToday },
    { key: 'overdue', label: t.tasks.filterOverdue },
    { key: 'upcoming', label: t.tasks.filterUpcoming },
    { key: 'completed', label: t.tasks.filterCompleted },
  ];

  const horizonEnd = addDays(todayISO, UPCOMING_HORIZON_DAYS);

  // Recurring series expanded into concrete occurrences for "Today" and
  // "Upcoming" — a flat backlog view can't sensibly show every future
  // date of an unbounded series, so this is capped at a real horizon
  // (see UPCOMING_HORIZON_DAYS) rather than generating forever.
  const occurrences = useMemo(
    () => expandTaskOccurrences(tasks, todayISO, horizonEnd, taskOccurrenceCompletions, taskOccurrenceSkips),
    [tasks, horizonEnd, taskOccurrenceCompletions, taskOccurrenceSkips],
  );

  // A SEPARATE, backward-looking expansion used only by "Overdue" — kept
  // independent from `occurrences` above (rather than widening its range)
  // so Today/Upcoming/Completed's existing behavior is untouched. Bounded
  // by PAST_HORIZON_DAYS for the same reason `occurrences` is bounded
  // forward: this only limits how many candidate dates are checked, it
  // never creates or persists any row.
  const pastRangeStart = addDays(todayISO, -PAST_HORIZON_DAYS);
  const pastOccurrences = useMemo(
    () => expandTaskOccurrences(tasks, pastRangeStart, todayISO, taskOccurrenceCompletions, taskOccurrenceSkips),
    [tasks, pastRangeStart, taskOccurrenceCompletions, taskOccurrenceSkips],
  );

  // A synthetic, TaskRow-renderable row for one occurrence — reuses the
  // series' own fields but anchors date/status to this specific occurrence,
  // so completing "today's" instance of a recurring task never touches
  // tomorrow's.
  function occurrenceAsTask(occ: (typeof occurrences)[number]): Task {
    return {
      ...occ.task,
      id: occ.task.recurrenceParentId ? occ.task.id : occ.seriesId,
      dueDate: occ.date,
      status: occ.completed ? 'completed' : 'todo',
    };
  }

  // The full Completed history, sorted NEWEST-COMPLETED-FIRST by the
  // actual completed_at timestamp (never by due date or occurrence
  // date). Recurring completions are resolved DIRECTLY from stored
  // completion records via resolveCompletedTaskOccurrences — not from
  // the forward-only `occurrences` expansion above, which only ever
  // spans [today, today+60 days] and therefore can never contain a
  // recurring occurrence that was completed yesterday or last week.
  // Because resolveCompletedTaskOccurrences works from the completion
  // records themselves (each one already says exactly which series and
  // date was completed), this never needs to walk a wide or unbounded
  // recurrence range just to discover what's been completed.
  const completedHistory = useMemo(() => {
    const nonRecurringCompleted = tasks
      .filter((task) => task.status === 'completed' && task.recurrenceType === 'none' && !task.recurrenceParentId)
      .map((task) => ({ row: task, editTask: task, completedAt: task.completedAt ?? '' }));

    const recurringCompleted = resolveCompletedTaskOccurrences(
      tasks,
      taskOccurrenceCompletionRecords,
      taskOccurrenceSkips,
    ).map((occ) => ({
      row: occurrenceAsTask(occ),
      editTask: occ.task,
      occurrenceDate: occ.date,
      seriesId: occ.seriesId,
      completedAt: occ.completedAt,
    }));

    return [...nonRecurringCompleted, ...recurringCompleted].sort((a, b) =>
      b.completedAt.localeCompare(a.completedAt),
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tasks, taskOccurrenceCompletionRecords, taskOccurrenceSkips]);

  const filtered: FilteredRow[] = useMemo(() => {
    if (filter === 'today') {
      return occurrences
        .filter((occ) => occ.date === todayISO && !occ.completed)
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task, // the real row (override or series parent) — never the synthetic display object
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));
    }
    if (filter === 'overdue') {
      // Ordinary tasks and occurrence overrides (both have
      // recurrenceType === 'none') are checked directly against their
      // own stored due date/time — no expansion or horizon needed here,
      // since this is just a plain field comparison regardless of how
      // old the date is.
      const nonRecurringOverdue: FilteredRow[] = tasks
        .filter(
          (task) =>
            task.recurrenceType === 'none' &&
            !task.recurrenceParentId &&
            task.status !== 'completed' &&
            task.dueDate &&
            isOccurrenceOverdue(task.dueDate, task.dueTime, todayISO, nowTimeHHMM),
        )
        .map((task) => ({ row: task, editTask: task }));

      // Still-recurring series: a missed PAST occurrence within the
      // bounded lookup window is overdue on its own — today's or future
      // occurrences of the same series are computed separately and are
      // never affected by a past one being overdue. Completed and
      // skipped occurrences are already excluded — completed via
      // `!occ.completed` (itself derived per-occurrence, never the
      // series parent's own status), skipped occurrences never appear in
      // `pastOccurrences` at all (expandTaskOccurrences excludes them).
      const recurringOverdue: FilteredRow[] = pastOccurrences
        .filter(
          (occ) => occ.isRecurring && !occ.completed && isOccurrenceOverdue(occ.date, occ.task.dueTime, todayISO, nowTimeHHMM),
        )
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task,
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));

      return [...nonRecurringOverdue, ...recurringOverdue].sort((a, b) => {
        const dateA = a.occurrenceDate ?? a.row.dueDate ?? '';
        const dateB = b.occurrenceDate ?? b.row.dueDate ?? '';
        if (dateA !== dateB) return dateB.localeCompare(dateA); // most recent date first
        // Same day: the more recently missed (later) time comes first;
        // an entry with no time at all sorts after one that has a time.
        const timeA = a.row.dueTime ?? '';
        const timeB = b.row.dueTime ?? '';
        if (!timeA && !timeB) return 0;
        if (!timeA) return 1;
        if (!timeB) return -1;
        return timeB.localeCompare(timeA);
      });
    }
    if (filter === 'upcoming') {
      const nonRecurringUpcoming: FilteredRow[] = occurrences
        .filter((occ) => !occ.isRecurring && occ.date > todayISO && !occ.completed)
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task,
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));

      // Fix (review): show only the SINGLE next upcoming incomplete
      // occurrence per recurring series — never every future date, which
      // previously produced 10+ identical-looking rows for a daily task.
      // Mirrors exactly the same "next pending occurrence" resolution
      // already used by "All" below. Completed/skipped occurrences are
      // already excluded from `occurrences` (skips never appear at all;
      // `!occ.completed` is checked per-occurrence, never the series
      // parent's own status) — so once the shown occurrence is completed
      // or skipped, this naturally resolves to whichever is next.
      // Occurrence overrides are unaffected: `occurrences` already
      // substitutes an override's own effective date/time wherever one
      // exists, with no special-casing needed here.
      const recurringSeriesIds = new Set(
        tasks.filter((task) => !task.recurrenceParentId && task.recurrenceType !== 'none').map((task) => task.id),
      );
      const recurringUpcoming: FilteredRow[] = [];
      for (const seriesId of recurringSeriesIds) {
        const next = occurrences
          .filter((occ) => occ.seriesId === seriesId && occ.date > todayISO && !occ.completed)
          .sort((a, b) => a.date.localeCompare(b.date))[0];
        if (next) {
          recurringUpcoming.push({
            row: occurrenceAsTask(next),
            editTask: next.task,
            occurrenceDate: next.date,
            seriesId: next.seriesId,
          });
        }
      }

      return [...nonRecurringUpcoming, ...recurringUpcoming].sort((a, b) =>
        (a.occurrenceDate ?? '').localeCompare(b.occurrenceDate ?? ''),
      );
    }
    if (filter === 'completed') {
      return completedHistory.slice(0, completedVisibleCount);
    }
    // "All" shows each task/series ONCE — never expanded into every
    // future date, since a flat list of every occurrence of every
    // recurring series would be unbounded and unreadable here (Today and
    // Calendar are where occurrences are browsed by date; this stays a
    // list of "things you have"). For a recurring series specifically,
    // this now shows its EFFECTIVE current/next pending occurrence
    // (reusing the same `occurrences` already computed above for
    // Today/Upcoming/Completed) instead of the series parent's own raw
    // stored fields — so an edited "This occurrence" override, or a
    // completed today, is correctly reflected here too, matching what
    // Today/Calendar already show for the same date. Falls back to the
    // raw series parent only if no pending occurrence exists within the
    // lookup horizon (e.g. an ended series) — same as before in that
    // edge case. Attaching occurrenceDate/seriesId here also means
    // tapping/checking this row goes through the exact same existing
    // this-occurrence-vs-series choice and per-occurrence completion
    // logic Today/Upcoming already use — no new logic, just correctly
    // supplying the context that logic already expects.
    return tasks
      .filter((task) => !task.recurrenceParentId)
      .map((task) => {
        if (task.recurrenceType === 'none') {
          return { row: task, editTask: task };
        }
        const pinnedDate = pinnedAllOccurrence[task.id];
        // If this series' occurrence was just toggled from All, keep
        // showing that exact date (now reflecting its current completion
        // state) instead of recomputing to whichever is next pending.
        const pinnedOccurrence = pinnedDate
          ? occurrences.find((occ) => occ.seriesId === task.id && occ.date === pinnedDate)
          : undefined;
        const nextOccurrence =
          pinnedOccurrence ??
          occurrences
            .filter((occ) => occ.seriesId === task.id && !occ.completed)
            .sort((a, b) => a.date.localeCompare(b.date))[0];
        if (!nextOccurrence) {
          return { row: task, editTask: task };
        }
        return {
          row: occurrenceAsTask(nextOccurrence),
          editTask: nextOccurrence.task,
          occurrenceDate: nextOccurrence.date,
          seriesId: nextOccurrence.seriesId,
        };
      });
  }, [
    filter,
    tasks,
    occurrences,
    pastOccurrences,
    todayISO,
    nowTimeHHMM,
    pinnedAllOccurrence,
    completedHistory,
    completedVisibleCount,
  ]);

  function openAdd() {
    setEditingTask(null);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
    setSheetOpen(true);
  }

  function openEdit(task: Task) {
    setEditingTask(task);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
    setSheetOpen(true);
  }

  function closeSheet() {
    setSheetOpen(false);
    setEditingTask(null);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
  }

  function openDetails(row: FilteredRow, initialAction: 'edit' | 'delete' | null = null) {
    setDetailsRow(row);
    setDetailsInitialAction(initialAction);
  }

  function closeDetails() {
    setDetailsRow(null);
    setDetailsInitialAction(null);
  }

  /** "Entire series" edit — always edits the series' own stored row, mirroring CalendarPage/TodayPage. */
  function editSeriesFromDetails() {
    if (!detailsRow) return;
    openEdit(detailsRow.editTask);
    closeDetails();
  }

  /** "This occurrence" edit — prefills with this occurrence's effective data, anchored to its own date. */
  function editOccurrenceFromDetails() {
    if (!detailsRow || !detailsRow.occurrenceDate || !detailsRow.seriesId) return;
    setEditingTask({ ...detailsRow.editTask, dueDate: detailsRow.occurrenceDate });
    setSheetHidesRecurrence(true);
    setOverrideContext({ seriesId: detailsRow.seriesId, date: detailsRow.occurrenceDate });
    closeDetails();
    setSheetOpen(true);
  }

  async function deleteSeriesFromDetails() {
    if (!detailsRow) return;
    await deleteTask(detailsRow.seriesId ?? detailsRow.editTask.id);
    closeDetails();
  }

  async function deleteOccurrenceFromDetails() {
    if (!detailsRow || !detailsRow.occurrenceDate || !detailsRow.seriesId) return;
    const overrideId = detailsRow.editTask.recurrenceParentId ? detailsRow.editTask.id : undefined;
    await deleteTaskOccurrence(detailsRow.seriesId, detailsRow.occurrenceDate, overrideId);
    closeDetails();
  }

  function handleToggle(row: { row: Task; occurrenceDate?: string; seriesId?: string }) {
    if (row.seriesId && row.occurrenceDate) {
      if (filter === 'all') {
        // Lock "All" to keep showing this exact occurrence (see
        // pinnedAllOccurrence above) rather than jumping to the next
        // pending one the instant it's marked complete.
        const seriesId = row.seriesId;
        const occurrenceDate = row.occurrenceDate;
        setPinnedAllOccurrence((prev) => ({ ...prev, [seriesId]: occurrenceDate }));
      }
      // A computed occurrence of a still-recurring series — toggle just
      // this date's completion, never the series' own row.
      void setTaskOccurrenceCompletion(row.seriesId, row.occurrenceDate, row.row.status !== 'completed');
    } else {
      toggleTask(row.row.id);
    }
  }

  return (
    <>
      <Header title={t.tasks.title} />

      <div className="tasks-page">
        <div className="tasks-filters scroll-row">
          {filters.map((f) => (
            <button
              key={f.key}
              className={`tasks-filter ${filter === f.key ? 'tasks-filter--active' : ''}`}
              onClick={() => setFilter(f.key)}
            >
              {f.label}
            </button>
          ))}
        </div>

        {tasksError && <p className="tasks-error-banner">{tasksError}</p>}

        <Card padding="md">
          {tasksLoading ? (
            <p className="tasks-loading">Loading your tasks…</p>
          ) : filtered.length === 0 ? (
            <EmptyState title={t.tasks.emptyTitle} subtitle={t.tasks.emptySubtitle} />
          ) : (
            filtered.map((row) => {
              const rowDate = row.occurrenceDate ?? row.row.dueDate;
              const isOverdueRow =
                row.row.status !== 'completed' &&
                Boolean(rowDate) &&
                isOccurrenceOverdue(rowDate as string, row.row.dueTime, todayISO, nowTimeHHMM);
              const dateLabel = rowDate
                ? formatTaskRowDateLabel(locale, rowDate, todayISO, {
                    today: t.tasks.filterToday,
                    tomorrow: t.tasks.tomorrow,
                    yesterday: t.tasks.yesterday,
                  })
                : undefined;
              return (
                <TaskRow
                  key={row.occurrenceDate ? `${row.seriesId}::${row.occurrenceDate}` : row.row.id}
                  task={row.row}
                  onToggle={() => handleToggle(row)}
                  onOpen={() => openDetails(row)}
                  onEditRequest={() => openDetails(row, 'edit')}
                  onDeleteRequest={() => openDetails(row, 'delete')}
                  hasReminder={reminders.some((r) => r.taskId === row.editTask.id)}
                  overdue={isOverdueRow}
                  dateLabel={dateLabel}
                  isRecurring={Boolean(row.occurrenceDate)}
                />
              );
            })
          )}
        </Card>

        {filter === 'completed' && completedHistory.length > 0 && (
          <div className="tasks-completed-footer">
            <p className="tasks-completed-footer__count">
              {formatString(t.tasks.completedCount, {
                shown: Math.min(completedVisibleCount, completedHistory.length),
                total: completedHistory.length,
              })}
            </p>
            {completedVisibleCount < completedHistory.length && (
              <button
                type="button"
                className="tasks-completed-footer__more"
                onClick={() => setCompletedVisibleCount((prev) => prev + COMPLETED_BATCH_SIZE)}
              >
                {t.tasks.viewOlderCompleted}
              </button>
            )}
          </div>
        )}
      </div>

      <IconButton aria-label={t.tasks.addTask} className="tasks-fab" onClick={openAdd}>
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
          <path d="M12 5v14M5 12h14" stroke="white" strokeWidth="2.2" strokeLinecap="round" />
        </svg>
      </IconButton>

      <AddTaskSheet
        open={sheetOpen}
        task={editingTask}
        existingReminder={
          editingTask ? reminders.find((r) => r.taskId === editingTask.id) ?? null : null
        }
        hideRecurrence={sheetHidesRecurrence}
        onClose={closeSheet}
        onSave={async (input) => {
          if (overrideContext) {
            await saveTaskOccurrenceOverride(overrideContext.seriesId, overrideContext.date, input);
          } else if (editingTask) {
            await updateTask(editingTask.id, input);
          } else {
            await addTask(input);
          }
          closeSheet();
        }}
        onDelete={
          editingTask && !overrideContext
            ? async () => {
                await deleteTask(editingTask.id);
                closeSheet();
              }
            : undefined
        }
      />

      <TaskDetailsSheet
        open={Boolean(detailsRow)}
        task={detailsRow ? detailsRow.row : null}
        reminder={detailsRow ? reminders.find((r) => r.taskId === detailsRow.editTask.id) ?? null : null}
        recurrenceLabel={
          detailsRow?.occurrenceDate
            ? describeRecurrence(
                {
                  type: (tasks.find((tsk) => tsk.id === detailsRow.seriesId) ?? detailsRow.editTask).recurrenceType,
                  daysOfWeek: (tasks.find((tsk) => tsk.id === detailsRow.seriesId) ?? detailsRow.editTask)
                    .recurrenceDaysOfWeek,
                },
                (tasks.find((tsk) => tsk.id === detailsRow.seriesId) ?? detailsRow.editTask).dueDate ??
                  detailsRow.occurrenceDate,
              )
            : null
        }
        isRecurringOccurrence={Boolean(detailsRow?.occurrenceDate && detailsRow?.seriesId)}
        initialAction={detailsInitialAction}
        onClose={closeDetails}
        onEdit={editSeriesFromDetails}
        onEditOccurrence={editOccurrenceFromDetails}
        onEditSeries={editSeriesFromDetails}
        onDeleteOccurrence={deleteOccurrenceFromDetails}
        onDeleteSeries={deleteSeriesFromDetails}
        onDelete={async () => {
          if (!detailsRow) return;
          await deleteTask(detailsRow.seriesId ?? detailsRow.editTask.id);
          closeDetails();
        }}
      />
    </>
  );
}
