import { useEffect, useMemo, useState } from 'react';
import Header from '../../components/layout/Header';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import TaskRow from '../../components/ui/TaskRow';
import EmptyState from '../../components/ui/EmptyState';
import IconButton from '../../components/ui/IconButton';
import { useLocale } from '../../i18n/LocaleContext';
import { useAppState } from '../../state/AppStateContext';
import { expandTaskOccurrences } from '../../lib/occurrences';
import { toISODate, addDays } from '../../lib/utils';
import type { Task } from '../../types/task';
import AddTaskSheet from './AddTaskSheet';
import './TasksPage.css';

type Filter = 'all' | 'today' | 'overdue' | 'upcoming' | 'completed';

// A reasonable planning horizon for expanding recurring series into the
// "Upcoming" list — showing every future occurrence forever would be
// both unbounded and overwhelming for a flat backlog-style view.
const UPCOMING_HORIZON_DAYS = 60;

// How far back "Overdue" searches for a missed recurring occurrence.
//
// PRODUCT RULE (explicit, not silently arbitrary): search each
// recurring series from its OWN start date forward — i.e., include
// every occurrence the series has ever had, with no artificial cutoff —
// bounded only by a ~10-year defensive ceiling that exists purely as a
// backstop against pathological data (e.g. a manually mis-entered due
// date decades in the past), never as a realistic day-to-day limit.
//
// This is safe and cheap because of how getOccurrencesInRange (see
// src/lib/recurrence.ts) already works: it clamps its actual search
// start to whichever is LATER — the range passed in, or the series' own
// due date — so passing a very early PAST_HORIZON_DAYS here never makes
// a young series scan further back than the day it actually started.
// The function also has its own internal 3660-iteration (~10 year) cap
// regardless of what range is requested, so this can never become an
// unbounded or performance-dangerous loop even for pathological input.
// No database rows are generated by any of this — it's purely an
// in-memory date-range walk repeated on every recompute.
const PAST_HORIZON_DAYS = 3650;

/**
 * Whether a specific occurrence date (with its own effective due time,
 * which for an override is the OVERRIDE's own time, and for a plain
 * recurring occurrence is the series' consistent time-of-day) is overdue
 * as of right now.
 *   - any date before today -> overdue
 *   - today, with a due time that has already passed -> overdue
 *   - today, with no due time, or a due time still ahead -> NOT overdue
 *     (a task due today with no time is only overdue starting tomorrow)
 */
function isOccurrenceOverdue(
  occurrenceDate: string,
  dueTime: string | undefined,
  todayISO: string,
  nowTimeHHMM: string,
): boolean {
  if (occurrenceDate < todayISO) return true;
  if (occurrenceDate === todayISO && dueTime && dueTime < nowTimeHHMM) return true;
  return false;
}

export default function TasksPage() {
  const { t } = useLocale();
  const {
    tasks,
    tasksLoading,
    tasksError,
    toggleTask,
    addTask,
    updateTask,
    deleteTask,
    saveTaskOccurrenceOverride,
    reminders,
    taskOccurrenceCompletions,
    taskOccurrenceSkips,
    setTaskOccurrenceCompletion,
  } = useAppState();
  const [filter, setFilter] = useState<Filter>('all');
  const [sheetOpen, setSheetOpen] = useState(false);
  const [editingTask, setEditingTask] = useState<Task | null>(null);
  const [sheetHidesRecurrence, setSheetHidesRecurrence] = useState(false);
  const [overrideContext, setOverrideContext] = useState<{ seriesId: string; date: string } | null>(null);
  type FilteredRow = { row: Task; editTask: Task; occurrenceDate?: string; seriesId?: string };
  const [choiceRow, setChoiceRow] = useState<FilteredRow | null>(null);

  // Drives "now" for overdue/date calculations below. Ticks once a
  // minute — never higher-frequency — which is exactly enough
  // resolution for a due TIME (HH:MM) to be detected as passed, and for
  // the date itself to correctly roll over at midnight, without a page
  // reload. A plain setInterval is used rather than requestAnimationFrame
  // or any per-second timer, since nothing here needs sub-minute
  // precision.
  const [now, setNow] = useState(() => new Date());
  useEffect(() => {
    const id = setInterval(() => setNow(new Date()), 60000);
    return () => clearInterval(id);
  }, []);

  const todayISO = toISODate(now);
  const nowTimeHHMM = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

  const filters: { key: Filter; label: string }[] = [
    { key: 'all', label: t.tasks.filterAll },
    { key: 'today', label: t.tasks.filterToday },
    { key: 'overdue', label: t.tasks.filterOverdue },
    { key: 'upcoming', label: t.tasks.filterUpcoming },
    { key: 'completed', label: t.tasks.filterCompleted },
  ];

  const horizonEnd = addDays(todayISO, UPCOMING_HORIZON_DAYS);

  // Recurring series expanded into concrete occurrences for "Today" and
  // "Upcoming" — a flat backlog view can't sensibly show every future
  // date of an unbounded series, so this is capped at a real horizon
  // (see UPCOMING_HORIZON_DAYS) rather than generating forever.
  const occurrences = useMemo(
    () => expandTaskOccurrences(tasks, todayISO, horizonEnd, taskOccurrenceCompletions, taskOccurrenceSkips),
    [tasks, horizonEnd, taskOccurrenceCompletions, taskOccurrenceSkips],
  );

  // A SEPARATE, backward-looking expansion used only by "Overdue" — kept
  // independent from `occurrences` above (rather than widening its range)
  // so Today/Upcoming/Completed's existing behavior is untouched. Bounded
  // by PAST_HORIZON_DAYS for the same reason `occurrences` is bounded
  // forward: this only limits how many candidate dates are checked, it
  // never creates or persists any row.
  const pastRangeStart = addDays(todayISO, -PAST_HORIZON_DAYS);
  const pastOccurrences = useMemo(
    () => expandTaskOccurrences(tasks, pastRangeStart, todayISO, taskOccurrenceCompletions, taskOccurrenceSkips),
    [tasks, pastRangeStart, taskOccurrenceCompletions, taskOccurrenceSkips],
  );

  // A synthetic, TaskRow-renderable row for one occurrence — reuses the
  // series' own fields but anchors date/status to this specific occurrence,
  // so completing "today's" instance of a recurring task never touches
  // tomorrow's.
  function occurrenceAsTask(occ: (typeof occurrences)[number]): Task {
    return {
      ...occ.task,
      id: occ.task.recurrenceParentId ? occ.task.id : occ.seriesId,
      dueDate: occ.date,
      status: occ.completed ? 'completed' : 'todo',
    };
  }

  const filtered: FilteredRow[] = useMemo(() => {
    if (filter === 'today') {
      return occurrences
        .filter((occ) => occ.date === todayISO && !occ.completed)
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task, // the real row (override or series parent) — never the synthetic display object
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));
    }
    if (filter === 'overdue') {
      // Ordinary tasks and occurrence overrides (both have
      // recurrenceType === 'none') are checked directly against their
      // own stored due date/time — no expansion or horizon needed here,
      // since this is just a plain field comparison regardless of how
      // old the date is.
      const nonRecurringOverdue: FilteredRow[] = tasks
        .filter(
          (task) =>
            task.recurrenceType === 'none' &&
            !task.recurrenceParentId &&
            task.status !== 'completed' &&
            task.dueDate &&
            isOccurrenceOverdue(task.dueDate, task.dueTime, todayISO, nowTimeHHMM),
        )
        .map((task) => ({ row: task, editTask: task }));

      // Still-recurring series: a missed PAST occurrence within the
      // bounded lookup window is overdue on its own — today's or future
      // occurrences of the same series are computed separately and are
      // never affected by a past one being overdue. Completed and
      // skipped occurrences are already excluded — completed via
      // `!occ.completed` (itself derived per-occurrence, never the
      // series parent's own status), skipped occurrences never appear in
      // `pastOccurrences` at all (expandTaskOccurrences excludes them).
      const recurringOverdue: FilteredRow[] = pastOccurrences
        .filter(
          (occ) => occ.isRecurring && !occ.completed && isOccurrenceOverdue(occ.date, occ.task.dueTime, todayISO, nowTimeHHMM),
        )
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task,
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));

      return [...nonRecurringOverdue, ...recurringOverdue].sort((a, b) =>
        (a.occurrenceDate ?? a.row.dueDate ?? '').localeCompare(b.occurrenceDate ?? b.row.dueDate ?? ''),
      );
    }
    if (filter === 'upcoming') {
      return occurrences
        .filter((occ) => occ.date > todayISO && !occ.completed)
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task,
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));
    }
    if (filter === 'completed') {
      const nonRecurringCompleted = tasks
        .filter((task) => task.status === 'completed' && task.recurrenceType === 'none')
        .map((task) => ({ row: task, editTask: task }));
      const recurringCompleted = occurrences
        .filter((occ) => occ.completed)
        .map((occ) => ({
          row: occurrenceAsTask(occ),
          editTask: occ.task,
          occurrenceDate: occ.date,
          seriesId: occ.seriesId,
        }));
      return [...nonRecurringCompleted, ...recurringCompleted];
    }
    // "All" shows each task/series ONCE — never expanded into every
    // future date, since a flat list of every occurrence of every
    // recurring series would be unbounded and unreadable here (Today and
    // Calendar are where occurrences are browsed by date; this stays a
    // list of "things you have"). For a recurring series specifically,
    // this now shows its EFFECTIVE current/next pending occurrence
    // (reusing the same `occurrences` already computed above for
    // Today/Upcoming/Completed) instead of the series parent's own raw
    // stored fields — so an edited "This occurrence" override, or a
    // completed today, is correctly reflected here too, matching what
    // Today/Calendar already show for the same date. Falls back to the
    // raw series parent only if no pending occurrence exists within the
    // lookup horizon (e.g. an ended series) — same as before in that
    // edge case. Attaching occurrenceDate/seriesId here also means
    // tapping/checking this row goes through the exact same existing
    // this-occurrence-vs-series choice and per-occurrence completion
    // logic Today/Upcoming already use — no new logic, just correctly
    // supplying the context that logic already expects.
    return tasks
      .filter((task) => !task.recurrenceParentId)
      .map((task) => {
        if (task.recurrenceType === 'none') {
          return { row: task, editTask: task };
        }
        const nextOccurrence = occurrences
          .filter((occ) => occ.seriesId === task.id && !occ.completed)
          .sort((a, b) => a.date.localeCompare(b.date))[0];
        if (!nextOccurrence) {
          return { row: task, editTask: task };
        }
        return {
          row: occurrenceAsTask(nextOccurrence),
          editTask: nextOccurrence.task,
          occurrenceDate: nextOccurrence.date,
          seriesId: nextOccurrence.seriesId,
        };
      });
  }, [filter, tasks, occurrences, pastOccurrences, todayISO, nowTimeHHMM]);

  function openAdd() {
    setEditingTask(null);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
    setSheetOpen(true);
  }

  function openEdit(task: Task) {
    setEditingTask(task);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
    setSheetOpen(true);
  }

  function closeSheet() {
    setSheetOpen(false);
    setEditingTask(null);
    setSheetHidesRecurrence(false);
    setOverrideContext(null);
  }

  /**
   * Fix (review, item 9): a recurring occurrence must never be edited by
   * silently opening the series parent directly — the user must
   * explicitly choose "This occurrence" or "Entire series" first. An
   * override row (recurrenceType === 'none' on the edited row itself) or
   * an ordinary, non-recurring task skips the choice and opens straight
   * into editing, exactly as before — only a still-recurring virtual
   * occurrence triggers the choice.
   */
  function handleRowTap(row: FilteredRow) {
    const isRecurringOccurrence = Boolean(row.occurrenceDate && row.editTask.recurrenceType !== 'none');
    if (isRecurringOccurrence) {
      setChoiceRow(row);
    } else {
      openEdit(row.editTask);
    }
  }

  function closeChoice() {
    setChoiceRow(null);
  }

  function chooseEditOccurrence() {
    if (!choiceRow || !choiceRow.occurrenceDate || !choiceRow.seriesId) return;
    setEditingTask({ ...choiceRow.editTask, dueDate: choiceRow.occurrenceDate });
    setSheetHidesRecurrence(true);
    setOverrideContext({ seriesId: choiceRow.seriesId, date: choiceRow.occurrenceDate });
    setChoiceRow(null);
    setSheetOpen(true);
  }

  function chooseEditSeries() {
    if (!choiceRow) return;
    openEdit(choiceRow.editTask);
    setChoiceRow(null);
  }

  function handleToggle(row: { row: Task; occurrenceDate?: string; seriesId?: string }) {
    if (row.seriesId && row.occurrenceDate && row.row.recurrenceType !== 'none') {
      // A computed occurrence of a still-recurring series — toggle just
      // this date's completion, never the series' own row.
      void setTaskOccurrenceCompletion(row.seriesId, row.occurrenceDate, row.row.status !== 'completed');
    } else {
      toggleTask(row.row.id);
    }
  }

  return (
    <>
      <Header title={t.tasks.title} />

      <div className="tasks-page">
        <div className="tasks-filters scroll-row">
          {filters.map((f) => (
            <button
              key={f.key}
              className={`tasks-filter ${filter === f.key ? 'tasks-filter--active' : ''}`}
              onClick={() => setFilter(f.key)}
            >
              {f.label}
            </button>
          ))}
        </div>

        {tasksError && <p className="tasks-error-banner">{tasksError}</p>}

        <Card padding="md">
          {tasksLoading ? (
            <p className="tasks-loading">Loading your tasks…</p>
          ) : filtered.length === 0 ? (
            <EmptyState title={t.tasks.emptyTitle} subtitle={t.tasks.emptySubtitle} />
          ) : (
            filtered.map((row) => {
              const rowDate = row.occurrenceDate ?? row.row.dueDate;
              const isOverdueRow =
                row.row.status !== 'completed' &&
                Boolean(rowDate) &&
                isOccurrenceOverdue(rowDate as string, row.row.dueTime, todayISO, nowTimeHHMM);
              return (
                <TaskRow
                  key={row.occurrenceDate ? `${row.seriesId}::${row.occurrenceDate}` : row.row.id}
                  task={row.row}
                  onToggle={() => handleToggle(row)}
                  onOpen={() => handleRowTap(row)}
                  hasReminder={reminders.some((r) => r.taskId === row.editTask.id)}
                  overdue={isOverdueRow}
                />
              );
            })
          )}
        </Card>
      </div>

      <IconButton aria-label={t.tasks.addTask} className="tasks-fab" onClick={openAdd}>
        <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
          <path d="M12 5v14M5 12h14" stroke="white" strokeWidth="2.2" strokeLinecap="round" />
        </svg>
      </IconButton>

      <AddTaskSheet
        open={sheetOpen}
        task={editingTask}
        existingReminder={
          editingTask ? reminders.find((r) => r.taskId === editingTask.id) ?? null : null
        }
        hideRecurrence={sheetHidesRecurrence}
        onClose={closeSheet}
        onSave={async (input) => {
          if (overrideContext) {
            await saveTaskOccurrenceOverride(overrideContext.seriesId, overrideContext.date, input);
          } else if (editingTask) {
            await updateTask(editingTask.id, input);
          } else {
            await addTask(input);
          }
          closeSheet();
        }}
        onDelete={
          editingTask && !overrideContext
            ? async () => {
                await deleteTask(editingTask.id);
                closeSheet();
              }
            : undefined
        }
      />

      {choiceRow && (
        <div className="add-task-overlay" role="dialog" aria-modal="true" aria-label="Edit recurring task">
          <Card padding="lg" className="tasks-occurrence-choice">
            <p className="tasks-occurrence-choice__title">Edit just this occurrence, or the whole series?</p>
            <div className="tasks-occurrence-choice__actions">
              <Button variant="ghost" fullWidth onClick={closeChoice}>
                Cancel
              </Button>
              <Button variant="secondary" fullWidth onClick={chooseEditOccurrence}>
                This occurrence
              </Button>
              <Button fullWidth onClick={chooseEditSeries}>
                Entire series
              </Button>
            </div>
          </Card>
        </div>
      )}
    </>
  );
}
